### ISSUE TITLE
Can it be responsive?

### ISSUE THREAD

**Issue by sudharsan1988** [react-designer/react-designer#12]
Sorry, I am not sure whether it's already responsive but i just curious to know whether it can be used in responsive design so that users can use the drag & drop image option on their mobile device/iPad/tablets

**Comment by jkarttunen** [comment]
You mean 'responsive' as in 'responsive layout' or 'as in 'supports touch events'?

**Comment by sudharsan1988** [comment]
Sorry, I meant to say, responsive layout.
