### ISSUE TITLE
Possible to use Images instead of reactangles, Primitives?

### ISSUE THREAD

**Issue by schmaluk** [react-designer/react-designer#22]
Hello,

wanted to ask, if it is possible to use Images instead of rectangles, which you could resize, rotate and move. Would be really helpful.

Thanks a ton

**Comment by vikas-0** [comment]
Yes I also want to know if it is possible to get external images

**Comment by mfpiccolo** [comment]
Did you ever figure out if that was possible? Thanks for doing the React upgrade compatibility BTW!

**Comment by kaidoj** [comment]
Is it possible?

**Comment by wassgha** [comment]
Added through #21 although images are serialized in base 64, might be nice to add a way to upload to a server
