### ISSUE TITLE
Cannot import react designer

### ISSUE THREAD

**Issue by ivoalexcorreia** [react-designer/react-designer#24]
Hi i'm trying to import the library using the following line on my application:
`import Designer, {Text, Rect} from 'react-designer';`

When i start the application with npm start, the compilation of my application fails with this error:
./src/App.js
Module not found: Can't resolve 'react-designer' in 'C:\Users\....'

Some help please!

**Comment by shubhroshekhar** [comment]
use 
import Designer, { Text, Rectangle } from 'react-designer/src/Designer';

**Comment by 10SPD** [comment]
Has anyone resolved this issue? I am still getting the same issue on the latest.

**Comment by anthonyalviz** [comment]
Great component, but unusable due to this issue. Bummer.

**Comment by Darshanak** [comment]
Is this issue resolved yet. ? i am getting same error - Can't resolve 'react-designer'

**Comment by MistrySaurabh** [comment]
> use
> import Designer, { Text, Rectangle } from 'react-designer/src/Designer';

I got this error 
<img width="467" alt="screen shot 2018-10-11 at 16 33 19" src="https://user-images.githubusercontent.com/16002832/46799822-70129800-cd73-11e8-8943-26646505aede.png">

**Comment by wassgha** [comment]
Fixed through #30 , will become available on the next release

**Comment by hartatovich** [comment]
not working on 1.1.0 version from npm

**Comment by Alexander530-tech** [comment]
I also have a same issue. my react-designer version is ^1.1.1.
but it was crashed.
the error is following as:
![image](https://user-images.githubusercontent.com/73733052/103152907-8747cf80-479d-11eb-8fcd-749570155a57.png)
