### ISSUE TITLE
Broken in Safari 8.0.7 on OSX 10.10.4

### ISSUE THREAD

**Issue by brekk** [react-designer/react-designer#4]
_http://fatiherikli.github.io/react-designer/_ : 

```
[Error] SyntaxError: Attempted to redefine property 'fontFamily'.
    (anonymous function) (bundle.js, line 26)
```

**Comment by fatiherikli** [comment]
I cannot reproduce on Safari 9.0.

Is there anyone who have an idea about how can I fix this?

**Comment by brekk** [comment]
I'm not 100%, but my guess is that somewhere `fontFamily` is being defined as a `const` and then it is trying to be redefined later on.

Guessing it lives in one of these files: https://github.com/fatiherikli/react-designer/search?utf8=✓&q=fontFamily

**Comment by fatiherikli** [comment]
I guess I found the problem. Could you try again? If it works, I'll release a minor version update.

**Comment by brekk** [comment]
Retried; same issue, but now it's on line 27.

**Comment by fatiherikli** [comment]
Weird. I'll try to downgrade my Safari to 8, and investigate.

**Comment by wassgha** [comment]
Closing for now, please reopen if this is still need.
