### ISSUE TITLE
What is the license of the project?

### ISSUE THREAD

**Issue by hargup** [react-designer/react-designer#62]
React Designer looks great and I would love use it, though the license of the project is unclear. The website [1] says its MIT licensed, though from the LICENSE file in the code [2], it appears the project is prorietary. Please clarify.

[1]: https://react-designer.github.io/react-designer/
[2]: https://github.com/react-designer/react-designer/blob/master/LICENSE

**Comment by aboodman** [comment]
FYI, I reached out to @fatiherikli and he changed the license to CC0. Thanks @fatiherikli !

**Comment by aboodman** [comment]
(this issue can be closed now)

**Comment by hargup** [comment]
Thanks  @aboodman and @fatiherikli for making the change :)
